export * from './IconWrapper'

export * from './PropertiesIcon'
export * from './DashboardIcon'
export * from './CustomersIcon'
export * from './BriefcaseIcon'
export * from './BuildingIcon'
export * from './UserIcon'
export * from './SquareCheckmarkIcon'
export * from './SquareCheckmarkAltIcon'
export * from './SquareIcon'
