import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'

export const CalSans = localFont({
  src: '../fonts/cal-sans.woff2',
  display: 'swap',
  variable: '--font-heading'
})

export const Roboto = Roboto_Flex({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-body'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${CalSans.variable} ${Roboto.variable}`}>{children}</body>
    </html>
  )
}
