create table "public"."organization_members" (
    "id" bigint generated by default as identity not null,
    "joined_at" timestamp with time zone not null default now(),
    "user" uuid not null,
    "organization" bigint not null
);


alter table "public"."organization_members" enable row level security;

CREATE UNIQUE INDEX organization_members_id_key ON public.organization_members USING btree (id);

CREATE UNIQUE INDEX organization_members_pkey ON public.organization_members USING btree (id);

CREATE UNIQUE INDEX users_id_key ON public.users USING btree (id);

alter table "public"."organization_members" add constraint "organization_members_pkey" PRIMARY KEY using index "organization_members_pkey";

alter table "public"."organization_members" add constraint "organization_members_id_key" UNIQUE using index "organization_members_id_key";

alter table "public"."organization_members" add constraint "organization_members_organization_fkey" FOREIGN KEY (organization) REFERENCES organizations(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."organization_members" validate constraint "organization_members_organization_fkey";

alter table "public"."organization_members" add constraint "organization_members_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."organization_members" validate constraint "organization_members_user_fkey";

alter table "public"."users" add constraint "users_id_key" UNIQUE using index "users_id_key";


